apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: q3eoupf9i-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:c763eb46dbde1020ba572b2220b3aa881a760cee@sha256:93165c9a630cbb3061f63f75657f0113a79feca9088bf02b0e3996dc2baa5481
          name: container-image
