apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q3eoupf9i-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q3eoupf9i-go 
  name: q3eoupf9i-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q3eoupf9i-go 
